Implement EFS
perfectsense/gyro-aws-provider pull request #303
Opened 2020-08-12 23:27 UTC by harjain99

Fixes #247

2020-08-13 15:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointFinder.java
> +        return client.describeAccessPoints(builder.build()).accessPoints();
If the id's are correct, but the resource does not exist, maybe catch that exception if it throws and return empty. Do this for all the `findaws()`

2020-08-13 17:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointResource.java
> +        List<AccessPointDescription> accessPointDescriptions = client.describeAccessPoints(r -> r.accessPointId(getId()))
Should also return false if the resource was not found. You will have to determine the exact exception for that.

2020-08-13 17:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointResource.java
> +                    .equals(LifeCycleState.AVAILABLE));
Same check is needed in the refresh as well.

Maybe good idea to separate out getting the access point into a method that both the delete and refresh can use.

2020-08-13 17:12 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointResource.java
> +                        .equals(LifeCycleState.DELETED));
Same as above

2020-08-13 17:12 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsCreationInfo.java
> +     * The POSIX group ID to apply to the root directory. Accepts values ranging from 0 to 4294967295.
```suggestion
     * The POSIX group ID to apply to the root directory. Accepts values ranging from ``0`` to ``4294967295``.
```

2020-08-13 17:12 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsCreationInfo.java
> +     * The POSIX user ID to apply to the root directory. Accepts values ranging from 0 to 4294967295.
```suggestion
     * The POSIX user ID to apply to the root directory. Accepts values ranging from ``0`` to ``4294967295``.
```

2020-08-13 17:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsCreationInfo.java
> +     * The POSIX permissions to apply to the root directory.
What are the list of permissions ?

2020-08-13 17:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsLifecyclePolicy.java
> +     * The value that describes the period of time that a file is not accessed, after which it transitions to the IA storage class.
Docs should specify the enum values

2020-08-13 17:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsPosixUser.java
> +     * The POSIX user ID used for all file system operations using the parent access point. Accepts values ranging from 0 to 4294967295.
```suggestion
     * The POSIX user ID used for all file system operations using the parent access point. Accepts values ranging from ``0`` to ``4294967295``.
```

2020-08-13 17:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsPosixUser.java
> +     * The POSIX user ID used for all file system operations using the parent access point. Accepts values ranging from 0 to 4294967295.
```suggestion
     * The POSIX user ID used for all file system operations using the parent access point. Accepts values ranging from ``0`` to ``4294967295``.
```

2020-08-13 17:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsRootDirectory.java
> +     * The path on the EFS file system to expose as the root directory to NFS clients using the access point.
```suggestion
     * The path on the EFS file system to expose as the root directory to NFS clients using the access point. (Required)
```

2020-08-13 17:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsRootDirectory.java
> +     * The POSIX IDs and permissions to apply to the access point's RootDirectory
Valid values specifying the enum

2020-08-13 17:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/FileSystemFinder.java
> +        return client.describeFileSystems(r -> r.fileSystemId(filters.get("id"))).fileSystems();
Handle the case where the specified id is correct but the item does not exist, should not error but return an empty list

2020-08-13 17:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/FileSystemFinder.java
> +        return client.describeFileSystems().fileSystems();
If you can, verify that when no file system is present this api does not error out

2020-08-24 15:03 UTC, harjain99 commented on src/main/java/gyro/aws/efs/EfsRootDirectory.java
> +     * The POSIX IDs and permissions to apply to the access point's RootDirectory
The variable represents a subresource.

2020-08-24 15:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsRootDirectory.java
> +     * The POSIX IDs and permissions to apply to the access point's RootDirectory
Should have the `@subresource` doc tag then

2020-09-02 19:25 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointFinder.java
> +        throw new IllegalArgumentException("Either 'id' or 'file-system-id' is required.");
```suggestion
        throw new IllegalArgumentException("Cannot query access-point without 'id' or 'file-system-id.");
```

2020-09-02 19:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointResource.java
> +            getTags().clear();
```suggestion
        getTags().clear();
        if (model.hasTags()) {
```

2020-09-02 19:30 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/AccessPointResource.java
> +            accessPoint = client.describeAccessPoints(r -> r.accessPointId(getId())).accessPoints().get(0);
Better to break this down into multiple statements with the null check
As we are only catching a specific exception, that will avoid a NPE being thrown.

2020-09-02 19:48 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/FileSystemResource.java
> +            client.putBackupPolicy(r -> r.fileSystemId(getId()).backupPolicy(getBackupPolicy().toBackupPolicy()));
This should have wait so that the status is complete from `Enabling` to `Enabled` or `Disabling` to `Disabled`

2020-09-02 19:48 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/FileSystemResource.java
> +            client.putBackupPolicy(r -> r.fileSystemId(getId()).backupPolicy(getBackupPolicy().toBackupPolicy()));
Same as above

2020-09-02 19:51 UTC, deepanjan90 commented on src/main/java/gyro/aws/efs/EfsBackupPolicy.java
> +     * The status of the file system's backup policy. Valid values are ``ENABLED``or ``ENABLING``or ``DISABLED``or ``DISABLING``. (Required)
Valid values should be `ENABLED` or `DISABLED`, the rest are transient values, even though I understand that the enum has them

2020-09-02 19:52 UTC, deepanjan90 requested changes
Update all the docs with has he following structure:
Valid values are ``A`` or ``B`` or ``C`` or ``D``
to:
Valid values are ``A``, ``B``, ``C`` or ``D``

2020-09-10 21:28 UTC, deepanjan90 requested changes
Everything works very well. Nice work 👍 

The resource names should probably be prefixed with efs, like `aws::efs-file-system`, `aws::efs-access-point` and `aws::efs-mount-target` so its a bit more clear what the resources are.

Changes for the above should reflect on the resource, finder, docs and examples.

2020-09-11 19:40 UTC, deepanjan90 approved these changes

2020-10-07 18:57 UTC, merged