Implement Codebuild
perfectsense/gyro-aws-provider pull request #316
Opened 2020-09-18 14:54 UTC by iHaoo

2020-09-18 14:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +            .build();
This should be part of `CodebuildCloudWatchLogsConfig` as a `to CloudWatchLogsConfig()` method

2020-09-18 15:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +            .build();
This should be part of `CodebuildS3LogsConfig ` as a `toS3LogsConfig()` method

2020-10-02 15:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildBuildStatusConfig.java
> +     * <https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codebuild/model/BuildStatusConfig.html#getContext--/>`_.
```suggestion
     * <https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codebuild/model/BuildStatusConfig.html#getContext>`_.
```

2020-10-02 15:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildBuildStatusConfig.java
> +     * <https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codebuild/model/BuildStatusConfig.html#getTargetUrl--/>`_.
```suggestion
     * <https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codebuild/model/BuildStatusConfig.html#getTargetUrl>`_.
```

2020-10-02 15:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildCodeCoverageReportSummary.java
> +    }
Documentation

2020-10-02 15:40 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * the type of the build output artifact.
```suggestion
     * The type of the build output artifact.
```

2020-10-02 15:41 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * The field that specifies for the output artifacts to be encrypted.
```suggestion
     * When set to ``true`` disables output artifacts to be encrypted.
```

2020-10-02 15:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +    }
Are both of them patterns ?

2020-10-02 15:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * The field that specifies if a name specified in the buildspec file overrides the artifact name.
```suggestion
     * When set to ``true`` the name specified in the buildspec file overrides the artifact name.
```

2020-10-02 15:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * The pattern that is used to name and store the output artifact.
Wring doc ??

2020-10-02 15:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +                "'location' cannot be empty if 'type' is 'S3'. Needs to specify the name of the output bucket."));
```suggestion
                "'location' cannot be empty if 'type' is set to 'S3'. "));
```

2020-10-02 15:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +                "'name' cannot be empty if 'type' is 'S3'. Needs to specify the name of the output artifact object."));
```suggestion
                "'name' cannot be empty if 'type' is 'S3'. "));
```

2020-10-02 15:51 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +        if (getLocation() == null && getType().equals("S3")) {
Better that just checking null, as we also don't want blank strings in this case
```suggestion
        if (!ObjectUtils.isBlank(getLocation()) && getType().equals("S3")) {
```

2020-10-02 15:51 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +        if (getName() == null && getType().equals("S3")) {
Same as above
```suggestion
        if (!ObjectUtils.isBlank(getName()) && getType().equals("S3")) {
```

2020-10-02 15:52 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +                "'encryption-disabled' option is valid only if 'type' is 'S3'."));
```suggestion
                "'encryption-disabled' can only be set if 'type' is set to 'S3'."));
```

2020-10-02 15:53 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +        if (getEncryptionDisabled() != null && !getType().equals("S3")) {
This can be set to false as well right ?

2020-10-02 15:56 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBadge.java
> +     * The field that specifies to generate a publicly accessible URL for the project's build badge.
```suggestion
     * When set to ``true`` generates a publicly accessible URL for the project's build badge.
```

2020-10-02 15:56 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBatchRestrictions.java
> +     * The list that specifies the compute types that are allowed for the batch build.
Is there a list of valid types ?

2020-10-02 15:57 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * The field that specifies if the build artifacts for the batch build should be combined into a single artifact
```suggestion
     * When set to ``true``  the build artifacts for the batch build are combined into a single artifact
```

2020-10-02 15:58 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * location.
```suggestion

```

2020-10-02 15:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * The restrictrions for the batch build.
```suggestion
     * The configuration for project build batch restrictions.
```

2020-10-02 15:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * The service role ARN for the batch build project.
```suggestion
     * The service role for the batch build project.
```

2020-10-02 15:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * The maximum amount of time that the batch build must be completed in.
is there a minimum value ?

2020-10-02 16:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +            : null);
This seems wrong, shouldn't the model be used ?

2020-10-02 16:02 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +            .build();
This should be part of a `toBatchRestriction()` method in `CodebuildProjectBatchRestrictions`

2020-10-02 16:04 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +        return environmentVariables;
```suggestion
        if (environmentVariables == null) {
            environmentVariables = new ArrayList<>();
        }
        
        return environmentVariables;
```

2020-10-02 16:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +        }
1. Whenever you are setting something conditionally in the copyFrom, always clear / set it to null, either to begin with, or as an else clause. The refresh when its being called gets all the field values from the state file of the previous run, so post refresh it is your responsibility to not only set new values but unset the old ones if necessary.

2. Using stream/lambda coding syntax to reduce code lines and variables while keeping the readability. 

```suggestion
        getEnvironmentVariables().clear();
        if (model.environmentVariables() != null) {
                model.environmentVariables().forEach(variable -> {
    	                CodebuildProjectEnvironmentVariable environmentVariable = newSubresource(
        	                CodebuildProjectEnvironmentVariable.class);
                        environmentVariable.copyFrom(variable);
                        getEnvironmentVariables().add(environmentVariable)
                });
        }
```

2020-10-02 16:17 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +        }
Set to null, reasoning from the last comment

2020-10-02 16:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +                "'image-pull-credentials-type' must be set to 'SERVICE_ROLE' to set 'registry-credential'."
```suggestion
                "'registry-credential' can only be set if 'image-pull-credentials-type' is set to 'SERVICE_ROLE'."
```

2020-10-02 16:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +        if (getRegistryCredential() != null && !getImagePullCredentialsType().equals("SERVICE_ROLE")) {
potential NPE if `getImagePullCredentialsType ` is null

2020-10-02 16:21 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +                null,
Even though the validation is based on two fields, this validation is pertaining to `registry-credential` 
```suggestion
               "registry-credential",
```

2020-10-02 16:22 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +                .build());
Shouldn't this be part of `CodebuildProjectEnvironmentVariable ` ?

2020-10-02 16:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +        }
set it null otherwise

2020-10-02 16:25 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +            setS3Logs(s3LogsConfig);
Set to null otherwise

2020-10-02 16:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +     * The Amazon CloudWatch Logs for a build project.
This is subresource that the user needs to configure

Something along the lines of `The configuration for cloud watch logs.`

2020-10-02 16:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +     * The logs built to an S3 bucket for a build project.
Similar to above

2020-10-02 16:27 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildGitSubmodulesConfig.java
> +     * Fetch Git submodules for the build project.
```suggestion
     * When set to ``true`` fetches Git submodules for the build project.
```

2020-10-02 16:35 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildCloudWatchLogsConfig.java
> +     * The current status of the logs in the Amazon CloudWatch Logs for a build project.
This enables/disables the log right ? Currently the doc makes it almost an output field

2020-10-02 17:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectFileSystemLocation.java
> +     * The mount options for a file system created by Amazon EFS.
Valid options ?

2020-10-02 18:36 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +            ));
Need to be consistent on the validation messages.

2020-10-02 18:37 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectTag.java
> +    @Regex("^([\\p{L}\\p{Z}\\p{N}_.:/=@+\\-]*)$")
Add the message so show a user friendly translation of the regex

2020-10-02 18:38 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectTag.java
> +    @Regex("^([\\p{L}\\p{Z}\\p{N}_.:/=@+\\-]*)$")
Add the message so show a user friendly translation of the regex

2020-10-02 18:41 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +    private List<String> securityGroupIds;
This will be a list of reference of security group resource.

2020-10-02 18:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +    private List<String> subnets;
This will be a list of reference of subnet resource

2020-10-02 18:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +    private String vpdId;
This will be a reference of vpc resource

2020-10-02 18:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +        }
@CollectionMax(5) is what you want

2020-10-02 18:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +        }
@CollectionMax(16) is what you want.

2020-10-02 18:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +     * The ty pe of webhook filter.
```suggestion
     * The type of webhook filter.
```

2020-10-02 18:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +     * pattern.
What does this mean exactly ?

2020-10-02 18:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupFinder.java
> +                .reportGroupArns(client.listReportGroups(r -> r.maxResults(100)).reportGroups())));
So what happens if there are more that 100 report groups ?

2020-10-02 18:50 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +     * Specifies a list of tags that are attached to the report group.
```suggestion
     * A list of tags that are attached to the report group.
```

2020-10-02 18:53 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +     * group.
```suggestion
     * When set to ``true`` deleting the report group automatically deletes all the reports under it. If set to ``false`` deleting a non empty report group is halted. 
```

2020-10-02 18:57 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +public class ReportGroupResource extends AwsResource implements Copyable<BatchGetReportGroupsResponse> {
BatchGetReportGroupsResponse is not the correct model, it has a list of the resource that you want.

This change will require the resource as well as the finder refactor

```suggestion
public class ReportGroupResource extends AwsResource implements Copyable<ReportGroups> {
```

2020-10-02 18:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +            response = client.batchGetReportGroups(r -> r.reportGroupArns(arns));
```suggestion
            response = client.batchGetReportGroups(r -> r.reportGroupArns(Collections.singletonList(getArn())));
```

2020-10-02 18:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +        }
Why are we catching and ignoring this ?

2020-10-02 19:01 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +        }
Why are we ignoring this ?

2020-10-02 19:01 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +        }
Why are we ignoring this ?

2020-10-02 19:02 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +    @Regex("[A-Za-z0-9][A-Za-z0-9\\-_]{1,254}")
have a user friendly message part of the regex

2020-10-02 19:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +public class WebhookResource extends AwsResource implements Copyable<BatchGetProjectsResponse> {
The model being passed to should be the model gyro is representing
Here gyro is representing `webhook` then the corresponding model from aws should be that and not some response. The model is primarily determined by the resource and not the finder and what is easier for the finder to return to.

```suggestion
public class WebhookResource extends AwsResource implements Copyable<Webhook> {
```

2020-10-02 19:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +        if (!changedFieldNames.isEmpty()) {
redundant check

2020-10-02 19:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +public class ProjectResource extends AwsResource implements Copyable<BatchGetProjectsResponse> {
The model should not be a response, it should be the singular model that the gyro resource is modeling

```suggestion
public class ProjectResource extends AwsResource implements Copyable<Project> {
```

2020-10-02 19:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +     * The ARN of the AWS IAM role.
Update doc

2020-10-02 19:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +     * The list of optional secondary artifacts.
```suggestion
     * The list of secondary artifacts.
```

2020-10-02 19:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +     * The list of optional secondary sources.
```suggestion
     * The list of secondary sources.
```

2020-10-02 19:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +     * The list of optional secondary source versions.
```suggestion
     * The list of secondary source versions.
```

2020-10-02 19:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +        if (!changedFieldNames.isEmpty()) {
redundant

2020-10-02 19:17 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +        }
Firstly we never club validations of multiple fields together.

Second all of these validations can be done using @CollectionMax() annotation

2020-10-02 19:18 UTC, deepanjan90 requested changes
1. For Boolean type fields:

Doc should be something along the lines of "When set to ``true`` <does something>"

 2. For Subresource type fields:

Doc should mention it as a configuration

Doc should also have a @subserosurce tag with the whole package path

 3. For copyFrom()

Refactor the position of this method to be on top refresh()

If conditionaly a variiable is set then the variable needs to set when teh conditional does not match
 - Either before checking the condition
 - Or in the else clause of the condition

 4. For validation messages:

Use phrases along the lines of `"Field" can be set if "Field" is set to "value"`, `"Field" cannot be set when condition` `"Field" can only be set condition`

 5. Finders

Specify usage docs

Add the filter fields and corresponding field documentations

Verify pagination of the api for the findAll() method

2020-10-02 21:23 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/CodebuildProjectFileSystemLocation.java
> +     * The mount options for a file system created by Amazon EFS.
No valid options available. Disregarding comment.

2020-10-07 15:44 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildCloudWatchLogsConfig.java
> +     * The current status of the logs in the Amazon CloudWatch Logs for a build project.
```suggestion
     * The current status of the logs in the Amazon CloudWatch Logs for a build project. Valid values are ``ENABLED`` or ``DISABLED``.
```

2020-10-07 16:16 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildGitSubmodulesConfig.java
> +     * submodules are fetched.
```suggestion
     * When set to ``true`` all Git submodules are fetched for the build project.
```

2020-10-07 16:19 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildGitSubmodulesConfig.java
> +    public Boolean getFetchSubmodules() {
Set the field as `Required`, if it is the only field in the subResource. It ensures that users don't pass in an empty subResource.

2020-10-07 16:29 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +    public LogsConfig toProjectLogsConfig() {
```suggestion
    public LogsConfig toLogsConfig() {
```

2020-10-07 16:40 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * encrypted.
```suggestion
     * When set to ``true`` the output artifacts are not encrypted.
```

2020-10-07 16:41 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +     * then the artifact name is not overridden.
```suggestion
     * When set to ``true`` the name specified in the buildspec file overrides the artifact name.
```

2020-10-09 21:44 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +     * The maximum amount of time that the batch build must be completed in.
No minimum value according to docs.

2020-10-12 12:45 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildCodeCoverageReportSummary.java
> +    @Min(0)
The `@Range` annotation can be used here instead.

2020-10-12 13:10 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +     * events. If 'type' is not 'EVENT', the pattern is a regular expression pattern.
```suggestion
     * The comma-separated string that specifies one or more events.
     * If ``type`` is not set to ``EVENT``, the pattern is a regular expression.
```

2020-10-13 14:03 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildCodeCoverageReportSummary.java
> +    @Min(0)
```suggestion
    @Range(min = 0, max = 100)
```

2020-10-13 14:13 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +    private String type;
The enum ``ArtifactsType`` can be used here instead.

2020-10-13 14:14 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +    private String namespaceType;
The enum ``ArtifactNamespace`` can be used here instead.

2020-10-13 14:20 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +    private String packaging;
The enum ``ArtifactPackaging`` can be used here instead.

2020-10-13 14:28 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +            .restrictions(getRestrictions().toBatchRestriction())
Check for a null pointer exception if there are no restrictions.

2020-10-13 14:31 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectCache.java
> +    private List<String> modes;
``List<CacheModes>`` can be used here

2020-10-13 14:31 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +
```suggestion
```

2020-10-13 14:34 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +    private String type;
The enum ``EnvironmentType`` can be used here.

2020-10-13 20:26 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +            return false;
Is the return statement required here?

2020-10-13 20:33 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +        client.updateReportGroup(r -> r
``deleteReports`` have an ``Updatable`` annotation as well. Can it be updated?

2020-10-13 20:36 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +    public List<String> getNames() {
Missing Docs.

2020-10-13 20:36 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/ProjectFinder.java
> +    public List<String> getNames() {
Missing docs

2020-10-13 20:42 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +        return "";
Subresources used in a list, need to have a unique primary key.

2020-10-13 20:50 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +}
Add a ``toWebhookFilter()`` to use in the ``WebhookResource``.

2020-10-15 17:13 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSourceVersion.java
> +}
No, `ProjectSourceVersion` type does not exist and source version is just a String.

2020-10-15 17:40 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +            return false;
Not sure, I thought it was necessary since otherwise the catch may error out with the exception. We can discuss with @deepanjan90

2020-10-15 17:42 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +        return "";
Need help figuring out what the unique primary key should be.

2020-10-15 17:53 UTC, iHaoo commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +        client.updateReportGroup(r -> r
At a second glance, the Updatable annotation should not be there. That field is not updatable, but only set upon creation.

2020-11-13 15:34 UTC, harjain99 requested changes

2020-11-13 15:34 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +    @Regex(value = "[A-Za-z0-9][A-Za-z0-9\\-_]{1,254}", message = "2-255 letters, numbers , hypehs, or underscores. The first character must be a letter or number.")
Remove regex, since the field is now a Resource type.

2020-11-13 15:34 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +     * The name of the build project.
```suggestion
     * The build project.
```

2020-11-13 15:34 UTC, harjain99 commented on examples/codebuild/webhook.gyro
> +    end
```suggestion
    project: "project-example-name"
```

Update example in WebhookResource as well

2020-11-13 15:34 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +    private WebhookResource webhook;
This should be an output field if it can't be configured

2020-11-16 20:26 UTC, harjain99 requested changes

2020-11-16 20:26 UTC, harjain99 commented on examples/codebuild/webhook.gyro
> +        compute-type: "BUILD_GENERAL1_SMALL
```suggestion
        compute-type: "BUILD_GENERAL1_LARGE"
```
Also, `BUILD_GENERAL1_SMALL` is incompatible with `ARM_CONTAINER`

2020-11-16 20:26 UTC, harjain99 commented on examples/codebuild/webhook.gyro
> +        location: "codebuild-us-east-2-242040583208-input-bucket/MessageUtil.zip"
The location should be a github repository.

2020-11-16 20:26 UTC, harjain99 commented on examples/codebuild/project.gyro
> +        compute-type: "BUILD_GENERAL1_SMALL"
`BUILD_GENERAL1_SMALL` is incompatible with `ARM_CONTAINER`

2020-11-16 20:26 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +        if (getReportBuildStatus() != null && !(getType().equals("GITHUB") || getType().equals("GITHUB_ENTERPRISE")
`reportBuildStatus` gets set to false in the copyFrom even if it is not set. Check to se if `reportBuildStatus` is `TRUE`.

2020-11-16 20:26 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +        if (getBuildStatusConfig() != null && !(getType().equals("GITHUB") || getType().equals("GITHUB_ENTERPRISE")
Check type against the enum.

2020-11-16 20:26 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +        if (getReportBuildStatus() != null && !(getType().equals("GITHUB") || getType().equals("GITHUB_ENTERPRISE")
Check type against the enum.

2020-11-16 20:26 UTC, harjain99 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +            && !getImagePullCredentialsType().equals("SERVICE_ROLE")) {
Check type against the enum.

2020-11-16 22:34 UTC, harjain99 approved these changes

2020-11-17 21:36 UTC, deepanjan90 commented on build.gradle
> +def releaseVersion = '0.99.5'
Release version changes are only done on releases.

2020-11-17 21:50 UTC, deepanjan90 commented on examples/codebuild/project.gyro
> +        "tag1": "value1"
```suggestion
        "tag": "value"
```

2020-11-17 22:11 UTC, deepanjan90 commented on examples/codebuild/project.gyro
> +    assume-role-policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codebuild.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
convert this into a json file

2020-11-29 21:21 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> +        if (webhook != null) {
Null check is redundant, we never call copy from with a null model in the first place.

2020-11-29 21:22 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookResource.java
> + *    end
Not needed as this is the doc for the webhook resource.

2020-11-29 21:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +            }
Not needed

2020-11-29 21:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +            return webhooks;
Not needed, as the final return will handle it.

2020-11-29 21:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/WebhookFinder.java
> +    private List<String> names;
Filters only work on singular item, so this should not be a list and only allow a single name.
Change the type, usage and docs accordingly.

2020-11-29 22:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +        }
Set this before for consistency and code reduction

2020-11-29 22:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +        }
Set this before the `if` for consistency and code reduction

2020-11-29 22:08 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +     * ``false`` deleting a non empty report group is halted.
```suggestion
     * When set to ``true`` deleting the report group automatically deletes all the reports under it.
```

2020-11-29 22:08 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> +    // Minimum required fields
```suggestion
```

2020-11-29 22:08 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupResource.java
> + * Creates a report group with the specified Name, Type, and Report Export Configuration.
```suggestion
 * Creates a report group.
```

2020-11-29 22:09 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ReportGroupFinder.java
> + *    report-group: $(external-query aws::report-group { arn: "arn:aws:codebuild:us-east-2:242040583208:report-group/report-group-test"})
We should not include values in docs that are not valid if rerun by someone else
```suggestion
 *    report-group: $(external-query aws::report-group { arn: ""})
```

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setVpcConfig(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setSecondarySources(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setSecondaryArtifacts(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setFileSystemLocations(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setCache(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setLogsConfig(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setBuildBatchConfig(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setTags(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setBadgeEnabled(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setEnvironment(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setSource(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectResource.java
> +            setArtifacts(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/ProjectFinder.java
> +    private List<String> names;
Finders with specific field should not accept a list by convention.
Change to singular update implementation, usage and docs

2020-11-29 22:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildWebhookFilter.java
> +     * The field that specifies if the pattern determines which webhook events that do not trigger a build.
```suggestion
     * If set to ``true`` excludes webhook events that are matched by the pattern specified.
```

2020-11-29 22:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +            setSecurityGroups(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +            setSubnets(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +            setVpc(null);
Set this before the `if` for consistency and code reduction

2020-11-29 22:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +     * The ID of the Amazon VPC.
```suggestion
     * The Amazon VPC resource.
```

2020-11-29 22:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +     * The list of security groups in the Amazon VPC.
```suggestion
     * One or more security groups part of the configured vpc to be used with the code build.
```

2020-11-29 22:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +     * The list of subnets in the Amazon VPC.
```suggestion
     * One or more subnets part of the configured vpc to be used with the code build.
```

2020-11-29 22:21 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildVpcConfig.java
> +     * The ID of the Amazon VPC.
```suggestion
     * The vpc resource to be associated with the code build.
```

2020-11-29 22:22 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildTestReportSummary.java
> +     * The number of nanoseconds to run all of the test cases in the report.
```suggestion
     * The time taken (in nanoseconds) to run all of the test cases in the report.
```

2020-11-29 22:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildS3ReportExportConfig.java
> +     * The name of the S3 bucket where the raw data of a report are exported.
```suggestion
     * The name of the S3 bucket where the raw data of a report are exported to.
```

2020-11-29 22:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReportExportConfig.java
> +            setS3ReportExportConfig(null);
Set this before the if for consistency and code reduction

2020-11-29 22:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReportExportConfig.java
> +     * The S3 bucket where the run of a export is exported.
run of a export ?

2020-11-29 22:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +            setTestSummary(null);
Set this before the if for consistency and code reduction

2020-11-29 22:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +            setExportConfig(null);
Set this before the if for consistency and code reduction

2020-11-29 22:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +            setCodeCoverageReportSummary(null);
Set this before the if for consistency and code reduction

2020-11-29 22:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +     * The type of the report that was run.
```suggestion
     * The type of the report.
```

2020-11-29 22:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +     * The date and time the report run occurred.
```suggestion
     * The report creation time.
```

2020-11-29 22:26 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildReport.java
> +     * The ARN of the report group associated with the report.
```suggestion
     * The ARN of the report group the report is part of.
```

2020-11-29 22:40 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectTag.java
> +    @Regex(value = "^([\\p{L}\\p{Z}\\p{N}_.:/=@+\\-]*)$", message = "0-255 letters, numbers, and specific symbols such as -, _, @, and /. ")
Make sure for an invalid value, the exception sentence is proper

2020-11-29 22:41 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSourceVersion.java
> +        return String.format("%s", getSourceIdentifier());
```suggestion
        return getSourceIdentifier();
```

2020-11-29 22:41 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSourceVersion.java
> +        return String.format("%s", getSourceIdentifier());
What if sourceIdentifier is null ?

2020-11-29 22:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +            setGitSubmodulesConfig(null);
Set this before the if for consistency and code reduction

2020-11-29 22:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +            setBuildStatusConfig(null);
Set this before the if for consistency and code reduction

2020-11-29 22:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +     * The Git clone depth for the build project.
```suggestion
     * The git clone depth for the build project.
```

2020-11-29 22:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectSource.java
> +     * The Git submodules configuration for the build project.
```suggestion
     * The git submodules configuration for the build project.
```

2020-11-29 22:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectFileSystemLocation.java
> +        return String.format("%s", getIdentifier());
What of identifier is null ?

2020-11-29 22:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironmentVariable.java
> +        return getName();
if the name is the primary key, the it cannot be updatable

2020-11-29 22:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectEnvironment.java
> +            setRegistryCredential(null);
Set this before the if for consistency and code reduction

2020-11-29 22:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectCache.java
> +        return modes;
```suggestion
        
        return modes;
```

2020-11-29 22:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBuildBatchConfig.java
> +            setRestrictions(null);
Set this before the if for consistency and code reduction

2020-11-29 22:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectBatchRestrictions.java
> +        return computedTypesAllowed;
```suggestion
        
        return computedTypesAllowed;
```

2020-11-29 22:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildProjectArtifacts.java
> +        return getName();
What if name is null ?

2020-11-29 22:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +            setS3Logs(null);
Set this before the if for consistency and code reduction

2020-11-29 22:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/codebuild/CodebuildLogsConfig.java
> +            setCloudWatchLogs(null);
Set this before the if for consistency and code reduction

2020-11-29 22:46 UTC, deepanjan90 requested changes
Inline changes

2020-12-14 21:45 UTC, deepanjan90 approved these changes

2020-12-15 13:25 UTC, merged