Convert arn field to TopicResource reference
perfectsense/gyro-aws-provider pull request #319
Opened 2020-10-01 20:50 UTC by iHaoo

2020-10-01 20:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +     * The topic of the SNS topic. (Required)
```suggestion
     * The SNS topic. (Required)
```

2020-10-01 21:02 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +                connectionNotification.connectionNotificationId()) : null);
Topic is a required field, so will always be present
```suggestion
        setTopic(findById(TopicResource.class, connectionNotification.connectionNotificationId()));
```

2020-10-02 14:29 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +                    .connectionNotificationArn(getTopic() != null ? getTopic().getArn() : null)
As get topic is required, it will never be null

2020-10-02 14:29 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +                    .connectionNotificationArn(getTopic() != null ? getTopic().getArn() : null)
Same as above

2020-10-02 14:29 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +                .connectionNotificationArn(getTopic() != null ? getTopic().getArn() : null)
Same as above

2020-10-02 14:33 UTC, deepanjan90 commented on src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java
> +                .connectionNotificationArn(getTopic() != null ? getTopic().getArn() : null)
This one as well

2020-10-02 14:38 UTC, deepanjan90 requested changes
Check in the examples where
```
aws::vpc-connectiom

end 
```
is used and update the arn filed to topic field

2020-10-02 20:42 UTC, iHaoo commented
Updated examples to add topic field

2020-10-04 16:36 UTC, deepanjan90 commented on examples/ec2/connection-notification.gyro
> +
References are single line, Complex types / Subresources are defined using the multiline block syntax 

```suggestion

    topic: "arn:aws:sns:us-east-2:242040583208:beam-instance-state"

```

2020-10-04 16:41 UTC, deepanjan90 requested changes
The example in the resource file needs to be changed as well
https://github.com/perfectsense/gyro-aws-provider/blob/master/src/main/java/gyro/aws/ec2/ConnectionNotificationResource.java#L55

2020-10-07 15:49 UTC, merged