Implement Auto Scaling Plan
perfectsense/gyro-aws-provider pull request #328
Opened 2020-10-20 19:55 UTC by iHaoo

2020-11-04 18:41 UTC, deepanjan90 commented on build.gradle
> +def releaseVersion = '0.99.5'
release version updates are only done for releases

2020-11-04 18:41 UTC, deepanjan90 commented on examples/autoscaling/autoscaling-plan.gyro
> +end
```suggestion
end

```

2020-11-04 18:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingApplicationSource.java
> +        return null;
Primary key can never be null

```suggestion
        return "";
```

2020-11-04 18:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedLoadMetricSpecification.java
> +            setDimensions(dimensions);
```suggestion
            
            setDimensions(dimensions);
```

2020-11-04 18:45 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedLoadMetricSpecification.java
> +        return null;
Primary key cannot be null

```suggestion
        return "";
```

2020-11-04 18:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedLoadMetricSpecification.java
> +    private String metricName;
Update the field, getter/setter and corresponding examples
```suggestion
    private String name;
```

2020-11-04 18:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedScalingMetricSpecification.java
> +    private String metricName;
Update the field, getter/setter and corresponding examples

```suggestion
    private String name;
```

2020-11-04 18:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedScalingMetricSpecification.java
> +            setDimensions(dimensions);
```suggestion
            
            setDimensions(dimensions);
```

2020-11-04 18:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedScalingMetricSpecification.java
> +        return null;
Primary key cannot be null.

```suggestion
        return "";
```

2020-11-04 20:04 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanFinder.java
> +    private List<String> scalingPlanNames;
This should be a single splan

2020-11-04 20:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> + * Plan Version.
A shorter description would be better

2020-11-04 20:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +     * The CloudFormation stack or a set of tag filters.
Are these the type of values that it can take ?

2020-11-04 20:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +     * The scaling instructions.
```suggestion
     * A list of scaling instruction configuration.
```

2020-11-04 20:12 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +     */
Doc needs the @subresource tag

2020-11-04 20:12 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +    @Required
An output field cannot be required

2020-11-04 20:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "Alphanumeric characters and symbols excluding basic ASCII control characters.")
an output field cannot/should not be validated

2020-11-04 20:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        }
```suggestion
        getScalingInstructions().clear();
        if (model.scalingInstructions() != null) {
            List<AutoScalingScalingInstruction> instructions = new ArrayList<>();
                       model.scalingInstructions().forEach(instruction -> {
                AutoScalingScalingInstruction scalingInstruction = newSubresource(
                    AutoScalingScalingInstruction.class);
                scalingInstruction.copyFrom(instruction);
                getScalingInstructions.add(scalingInstruction);
            });
        } 
```

2020-11-04 20:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        }
Why are we catching these exceptions ?
The refresh should only be catching a specific exception that might occur when the resource does not exist.

Every other exception needs to be let go.

If there is a specific exception then we catch that, otherwise we filter the generic exception based on error code and/or message and uses that.

2020-11-04 20:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        copyFrom(response.scalingPlans().get(0));
what if scalingPlans are empty

2020-11-04 20:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        client.deleteScalingPlan(r -> r
```suggestion
        
        client.deleteScalingPlan(r -> r
```

2020-11-04 20:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +
```suggestion
```

2020-11-04 20:24 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPredefinedLoadMetricSpecification.java
> +        return null;
Primary key cannot be null

2020-11-04 20:33 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPredefinedScalingMetricSpecification.java
> +        return null;
Primary key cannot be null

2020-11-04 20:34 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The ID of the resource.
What resource are we talking about, the doc seems very generic

2020-11-04 20:34 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The forecast max capacity behavior that should be applied to the resource.
Valid values ??

2020-11-04 20:35 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The predictive scaling mode.
Valid values ??

2020-11-04 20:36 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The predefined load metric to use for predictive scaling.
@subresource tag

2020-11-04 20:36 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The customized load metric for predictive scaling.
missing @subresource tag

2020-11-04 20:37 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +     * The target tracking configurations.
Missing @subresource tags.

2020-11-04 20:38 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +        return String.format("%s, instruction", getResourceId());
This primary key looks a bit weird.
It will output something like `<resource-id>, instruction` which does not tell much.

2020-11-04 20:39 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +        return null;
primary key cannot be null

2020-11-04 20:40 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +    }
Can you create a tagfilter with no key or no value as none of them are required

2020-11-04 20:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTargetTrackingConfiguration.java
> +     * When set to ``true`` the scale in by the target tracking scaling policy is disabled.
```suggestion
     * When set to ``true``, the scale in by the target tracking scaling policy is disabled.
```

2020-11-04 20:43 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTargetTrackingConfiguration.java
> +     * The customized metric.
Missing @subresource tag

2020-11-04 20:44 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTargetTrackingConfiguration.java
> +     * The estimated time, in seconds, until a new instance can contribute to the CloudWatch metrics.
```suggestion
     * The estimated time (in seconds) until a new instance can contribute to the CloudWatch metrics.
```

2020-11-04 20:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +        }
Refactor similar to https://github.com/perfectsense/gyro-aws-provider/pull/328/files#r517605911

2020-11-04 20:47 UTC, deepanjan90 requested changes
Inline changes.

Review the code and make sure to do the following for all instances:

 - Where ever a subresource/complex type is used the documentation needs to have the @subresource tag.
 - For all enum type variables, @Validstrings needs to be added, so that the doc can have the valid values in it.
 - Subresource/complex type cannot have null as the primary key

2020-11-06 20:57 UTC, iHaoo commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> + * Plan Version.
Double check to verify if the new description is short enough.

2020-11-06 21:25 UTC, iHaoo commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +     * The CloudFormation stack or a set of tag filters.
This field is either going to be using the cloudFormationStackArn or tagFilters field since only one can be picked.

2020-11-06 22:08 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> + * Plan Version.
`Creates a Scaling plan`
That is how other resource have their one liner description as well.

2020-11-06 22:48 UTC, iHaoo commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +        return String.format("%s, instruction", getResourceId());
Changed it to `String.format("%s", getCustomizedLoadMetricSpecification().getName())`, is that acceptable?

2020-11-12 19:22 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingApplicationSource.java
> +        }
not required as you are already clearing the map

2020-11-12 19:57 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingApplicationSource.java
> +    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "Alphanumeric characters and symbols excluding basic ASCII control characters.")
If only a Cloudformation stack arn is required, then do we even need to verify if it matches a regex or not. Cause even if it does, the only acceptable string would be a valid cloudformation stack arn.

2020-11-12 19:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanFinder.java
> + *    project: $(external-query aws::autoscaling-plan { scaling-plan-names: ['scaling-plan-example']}
```suggestion
 *    project: $(external-query aws::autoscaling-plan { scaling-plan-name: 'scaling-plan-example'}
```

2020-11-12 19:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanFinder.java
> +    /**
```suggestion
    
    /**
```

2020-11-12 20:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanFinder.java
> +        return client.describeScalingPlans(r -> r.scalingPlanNames(filters.get("scaling-plan-names"))).scalingPlans();
```suggestion
        return client.describeScalingPlans(r -> r.scalingPlanNames(filters.get("scaling-plan-name"))).scalingPlans();
```

2020-11-12 20:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +    private String scalingPlanName;
Change the name across all getters setters and examples bot docs and .gyro files
```suggestion
    private String Name;
```

2020-11-12 20:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        }
For consistency with the lower block
```suggestion
        setApplicationSource(null);
        if (model.applicationSource() != null) {
            AutoScalingApplicationSource applicationSource = newSubresource(AutoScalingApplicationSource.class);
            applicationSource.copyFrom(model.applicationSource());
            setApplicationSource(applicationSource);
        } 
```

2020-11-12 20:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        "UpdateFailed" })
output fields are not validated

2020-11-12 20:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +    public Long getScalingPlanVersion() {
Output ??

2020-11-12 20:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        setScalingPlanVersion(response.scalingPlanVersion());
if your calling refresh, is this really needed ?

2020-11-12 20:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingPlanResource.java
> +        client.updateScalingPlan(r -> r
Does updating a scaling plan change its version ?

2020-11-12 20:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "Alphanumeric characters and symbols excluding basic ASCII control characters.")
The regex becomes part of a full sentence.  Verify how this looks by triggering the validation.
```suggestion
    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "alphanumeric characters and symbols excluding basic ASCII control characters.")
```

2020-11-12 20:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "Alphanumeric characters and symbols excluding basic ASCII control characters.")
Same as above
```suggestion
    @Regex(value = "[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*", message = "alphanumeric characters and symbols excluding basic ASCII control characters.")
```

2020-11-12 20:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +        return getKey();
Basing off of https://github.com/perfectsense/gyro-aws-provider/pull/328/files#r517618274
What happens if key is empty

2020-11-12 20:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTargetTrackingConfiguration.java
> +     * The amount of time, in seconds, after a scale out activity completes before another can start.
```suggestion
     * The amount of time in seconds, after a scale out activity completes before another can start.
```

2020-11-12 20:15 UTC, deepanjan90 requested changes
Minor changes inline

2020-11-17 20:54 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedLoadMetricSpecification.java
> +        return dimensions;
```suggestion
        
        return dimensions;
```

2020-11-17 20:55 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingApplicationSource.java
> +        return tagFilters;
```suggestion
        
        return tagFilters;
```

2020-11-17 20:56 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedScalingMetricSpecification.java
> +        return dimensions;
```suggestion
        
        return dimensions;
```

2020-11-17 21:24 UTC, deepanjan90 requested changes
Minor changes inline

2020-11-18 21:36 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingCustomizedScalingMetricSpecification.java
> +    List<AutoScalingMetricDimension> dimensions;
```suggestion
    private List<AutoScalingMetricDimension> dimensions;
```

2020-11-18 21:38 UTC, deepanjan90 requested changes
1 inline comment

Example not working

2020-11-24 18:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingApplicationSource.java
> +    private List<AutoScalingTagFilter> tagFilters;
A validation should be in place as one of them is required

2020-11-24 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTagFilter.java
> +    @Range(min = 0, max = 20)
Why not use CollectionMax(20) ?

2020-11-24 18:28 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingTargetTrackingConfiguration.java
> +        return String.format("%s", getCustomizedScalingMetricSpecification() != null ? getCustomizedScalingMetricSpecification().getName() : "");
Also make target value required.
```suggestion
        return String.valueOf(getTargetValue());
```

2020-11-24 18:29 UTC, deepanjan90 commented on src/main/java/gyro/aws/autoscaling/AutoScalingScalingInstruction.java
> +        return String.format("%s", getResourceId());
```suggestion
        return getResourceId();
```

2020-11-24 18:31 UTC, deepanjan90 commented on examples/autoscaling/autoscaling-plan.gyro
> +        cloud-formation-stack-arn: "arn:aws:cloudformation:us-east-2:242040583208:stack/example-stack/e95a0400-192f-11eb-8eb9-0a36006b772c"
This Cloud-formation resource does not exist, also we do not manage the cloud-formation resource as of now
Better to replace the source with an autoscale group, that we can create as well in the example

2020-11-24 18:31 UTC, deepanjan90 requested changes
Inline changes

2020-12-15 20:20 UTC, merged