Implement ApiGatewayV2
perfectsense/gyro-aws-provider pull request #330
Opened 2020-11-02 20:55 UTC by harjain99

Fixes #286

2020-11-04 21:08 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiCors.java
> +        }
Remove the extra spaces after each of the statements inside the `if` block

2020-11-04 21:09 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiDomainNameConfiguration.java
> +     * The endpoint type.
Valid values ?

2020-11-04 21:09 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiDomainNameConfiguration.java
> +     * The Transport Layer Security (TLS) version of the security policy for this domain name.
Valid values

2020-11-04 21:09 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiFinder.java
> +public class ApiFinder extends AwsFinder<ApiGatewayV2Client, Api, ApiResource> {
ApiGateway maybe ?

2020-11-04 21:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiResource.java
> +public class ApiResource extends AwsResource implements Copyable<Api> {
ApiGateway resource maybe.
Api seems pretty generic

2020-11-04 21:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiResource.java
> +
```suggestion
```

2020-11-04 21:14 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiResource.java
> +                getId());
if the arn is not exposed by the model stil a good idea to save it in an output field

2020-11-04 21:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/AuthorizerResource.java
> +@Type("authorizer")
To make it less generic 
```suggestion
@Type("api-gateway-authorizer")
```

2020-11-04 21:16 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DeploymentFinder.java
> +@Type("deployment")
Similar as above to make it less generic
```suggestion
@Type("api-gateway-deployment")
```

2020-11-04 21:17 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DomainNameResource.java
> +@Type("domain-name")
Simiarr as before to make it less generic
```suggestion
@Type("api-gateway-domain-name")
```

2020-11-04 21:18 UTC, deepanjan90 requested changes
Refactor the resource names by appending `api-gateway` so that the resource names are not super generic, like `domain` and `integrations`

2020-11-13 16:44 UTC, deepanjan90 commented on examples/apigatewayv2/api.gyro
> +# Websocket api
Break this into two files, so its clear and one can just gyro up a full example

2020-11-13 16:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiDomainNameConfiguration.java
> +        if (getCertificate() != null) {
Is the null check required, as the `certificate` field is required ?

2020-11-13 16:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiDomainNameConfiguration.java
> +        DescribeCertificateResponse response = client.describeCertificate(r -> r.certificateArn(getCertificate().getArn()));
is this needed ?

2020-11-13 16:48 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiJwtConfiguration.java
> +        setAudiences(model.hasAudience() ? model.audience() : null);
If model-audinece is null it will set it to null right ?
```suggestion
        setAudiences(model.audience());
```

2020-11-13 16:49 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiMappingFinder.java
> +            apiMappings.removeIf(i -> !i.apiMappingId().equals(filters.get("id")));
what happens if the user did not set an id

2020-11-13 16:51 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiMappingResource.java
> +    private DomainNameResource domainName;
missing copyfrom

2020-11-13 16:59 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiRouteSettings.java
> +        }
What happens if all of them are null ?

2020-11-13 17:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/AuthorizerFinder.java
> +        return authorizers;
One liner ??
```suggestion
        return getApis(client).stream()
            .map(api -> client.getAuthorizers(r -> r.apiId(api)).items())
            .flatMap(List::stream)
            .collect(Collectors.toList());
```

2020-11-13 17:09 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/AuthorizerResource.java
> +    private ApiResource api;
Not set in copyfrom

2020-11-13 17:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DeploymentFinder.java
> +        return deployments;
One liner based on the earlier comment ?

2020-11-13 17:10 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DeploymentResource.java
> +    @Output
Missing doc

2020-11-13 17:13 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DomainNameResource.java
> +
```suggestion
```

2020-11-13 17:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/IntegrationFinder.java
> +        return integrations;
One liner based off of previous comment

2020-11-13 17:15 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/IntegrationResponseFinder.java
> +        return integrationResponses;
One liner based off of the previous comment

2020-11-13 17:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/IntegrationResponseResource.java
> +    private IntegrationResource integration;
Missing copy from

2020-11-13 17:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ModelFinder.java
> +        return models;
One liner based off of previous comment

2020-11-13 17:25 UTC, deepanjan90 reviewed
Minor inline comments
They are not complete, so try to generalize and refactor for all wherever applicable

2020-11-17 14:39 UTC, harjain99 commented on src/main/java/gyro/aws/apigatewayv2/ApiMappingFinder.java
> +            apiMappings.removeIf(i -> !i.apiMappingId().equals(filters.get("id")));
Then, we don't filter based on id and return all the api-mappings to the domain-name.

2020-11-17 15:15 UTC, harjain99 commented on src/main/java/gyro/aws/apigatewayv2/ApiRouteSettings.java
> +        }
The api assumes the `ApiRouteSettings` null if none of the fields are configured.

2020-11-29 22:47 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/package-info.java
> +import gyro.core.resource.DocGroup;
```suggestion
import gyro.core.resource.DocGroup;

```

2020-11-29 22:48 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/VpcLinkResource.java
> +        }
Clear the lists to begin with

2020-11-29 22:48 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/VpcLinkResource.java
> + *         tags: {
```suggestion
 *
 *         tags: {
```

2020-11-29 22:52 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/DomainNameResource.java
> +            setDomainNameConfigurations(null);
Set this before the if for consistency and code reduction

2020-11-29 22:56 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiResource.java
> +            setTags(null);
Set this before the if for consistency and code reduction

2020-11-29 22:57 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/ApiCors.java
> +        }
Set this before the if for consistency and code reduction

2020-11-29 22:58 UTC, deepanjan90 requested changes
Minor inline changes

2020-12-07 21:46 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/AuthorizerResource.java
> +     * The name of the authorizer. (Required)
```suggestion
     * The name of the authorizer.
```

2020-12-07 22:00 UTC, deepanjan90 requested changes
- 1 inline minor doc change

 - Add tags to resources in example like vpc, subnet and security group which dont have names. The "Name" tag is how we can identify them. It helps if for some reason one needs to manually clean up, to track which resources were created for which dependent resources.

 - All the finders should have pagination for the findAws() method, for reference look at : https://github.com/perfectsense/gyro-aws-provider/blob/master/src/main/java/gyro/aws/cloudwatch/EventRuleFinder.java#L57-L74

 - While running the api.gyro example running into the following:
```
+ Creating aws::api-gateway-route example-route
· api: aws::api-gateway example-api
· authorization-scopes: [ 'example-scope' ]
· authorization-type: JWT
· authorizer: aws::api-gateway-authorizer example-authorizer
· route-key: 'ANY /api/example/route'
· target: 'integrations/bicxh4j'

Error: Can't create aws::api-gateway-route example-route resource!

Caused by: Unexpected error: software.amazon.awssdk.services.apigatewayv2.model.BadRequestException: Unable to find route target of type integrations with ID bicxh4j (Service: ApiGatewayV2, Status Code: 400, Request ID: bd3778b8-6c7d-4758-971b-95e35f6852b7, Extended Request ID: null)
```

2020-12-14 22:18 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/VpcLinkResource.java
> +     * The list of subnet IDs to include in the VPC link.
```suggestion
     * The list of subnets to include in the VPC link.
```

2020-12-14 22:19 UTC, deepanjan90 commented on src/main/java/gyro/aws/apigatewayv2/VpcLinkResource.java
> +     * The list of security group IDs for the VPC link.
```suggestion
     * The list of security groups for the VPC link.
```

2020-12-18 18:38 UTC, merged