Implement DynamoDB Accelerator (DAX)
perfectsense/gyro-aws-provider pull request #331
Opened 2020-11-17 00:10 UTC by iHaoo

Fixes #250

2020-11-29 22:59 UTC, deepanjan90 commented on examples/dax/cluster.gyro
> +    iam-role-arn: "arn:aws:iam::242040583208:role/service-role/DAXtoDynamoDB"
Create a role resource and associate that

2020-11-29 23:00 UTC, deepanjan90 commented on examples/dax/subnet-group.gyro
> +    subnet-ids: ["subnet-07473edcb6aa2fff2"]
Create a vpc and atleast 2 subnets and then associate those here as references

2020-11-29 23:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxClusterFinder.java
> +    private List<String> names;
The specific finder should only take in a single value for filtering

2020-11-29 23:01 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxClusterResource.java
> +        return availabilityZones;
```suggestion
        
        return availabilityZones;
```

2020-11-29 23:02 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxClusterResource.java
> +        return securityGroupIds;
```suggestion
        
        return securityGroupIds;
```

2020-11-29 23:02 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxNode.java
> +     * The endpoint of the node.
```suggestion
     * The endpoint configuration of the node.
```

2020-11-29 23:03 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxNode.java
> +        return String.format("%s", getId());
What of the id is null ?

2020-11-29 23:03 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxNode.java
> +            setEndpoint(null);
Set this before the if for consistency and code reduction

2020-11-29 23:03 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxParameterGroupFinder.java
> +    private List<String> names;
Should be singular as mentioned earlier.

2020-11-29 23:04 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxParameterGroupResource.java
> +     */
Subresource tag missing.

2020-11-29 23:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxParameterGroupResource.java
> +        refresh();
No need to call this, as no output field present.

2020-11-29 23:05 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxParameterNameValue.java
> +        return String.format("%s", getName());
What of name is null ?

2020-11-29 23:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxSecurityGroupMembership.java
> +        return String.format("%s", getSecurityGroupIdentifier());
What if SecurityGroupIdentifier is null ?

2020-11-29 23:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxSubnet.java
> +        return String.format("%s", getIdentifier());
What if Identifier is null ?

2020-11-29 23:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxSubnetGroupFinder.java
> +    private List<String> names;
Should be singular. Same as earlier.

2020-11-29 23:06 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxSubnetGroupResource.java
> +    private List<String> subnetIds;
Should be a reference to the subnet resource

2020-11-29 23:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxSubnetGroupResource.java
> +    private String vpcId;
Should be a reference to the vpc resource

2020-11-29 23:07 UTC, deepanjan90 commented on src/main/java/gyro/aws/dax/DaxTag.java
> +        return String.format("%s", getKey());
What if key is null ?

2020-11-29 23:09 UTC, deepanjan90 requested changes
Inline changes.

keep mindful about two scenarios:
 - when associating a primary key
     - Check to see if the field can be null, if so, it cannot be used as a primary key
     - If only a single field is used for the primary key, string.format is not necessary.

2020-12-03 21:10 UTC, iHaoo commented on src/main/java/gyro/aws/dax/DaxTag.java
> +        return String.format("%s", getKey());
Doesn't @Required on key handle for a null key?

2020-12-03 22:06 UTC, deepanjan90 commented on examples/dax/cluster.gyro
> +end
```suggestion
end

```

2020-12-03 22:06 UTC, deepanjan90 commented on examples/dax/dax-role-policy.json
> +}
```suggestion
}

```

2020-12-16 13:29 UTC, merged