Implement ECR
perfectsense/gyro-aws-provider pull request #380
Opened 2021-01-20 22:32 UTC by harjain99

Fixes #289

2021-01-21 17:22 UTC, deepanjan90 commented on examples/ecr/repository.gyro
> +    end
I feel Lifecycle policy resource should be a direct field such that

```
lifecycle-policy: 'lifecycle-policy.json'
```

2021-01-21 17:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/ecr/EcrRepositoryResource.java
> + * Create VPN Gateway.
ECR ?

2021-01-21 17:23 UTC, deepanjan90 commented on src/main/java/gyro/aws/ecr/EcrRepositoryResource.java
> +    public EcrRepositoryPolicyResource getPolicy() {
Missing @Updatable tag ?

2021-01-21 17:30 UTC, deepanjan90 commented on src/main/java/gyro/aws/ecr/EcrRepositoryResource.java
> +    @Id
Try and figure out how is the ECR resource used by other resource, and if they use the name of the resource or the arn to reference it.
That will determine if @ID should be part of the name or arn getter

2021-01-21 17:30 UTC, deepanjan90 commented on src/main/java/gyro/aws/ecr/EcrRepositoryFinder.java
> + * Query repository.
```suggestion
 * Query ECR repository.
```

2021-01-21 17:32 UTC, deepanjan90 requested changes
Inline comments

2021-01-22 13:28 UTC, harjain99 commented on src/main/java/gyro/aws/ecr/EcrRepositoryResource.java
> +    public EcrRepositoryPolicyResource getPolicy() {
`EcrRepositoryPolicyResource` is a sub-resource with its own create/update/delete, so I believe it doesn't need and Updatable tag, right?

2021-01-22 15:11 UTC, deepanjan90 commented on src/main/java/gyro/aws/ecr/EcrRepositoryResource.java
> + *         end
Update the examples

2021-02-09 22:47 UTC, deepanjan90 approved these changes

2021-02-09 22:48 UTC, merged