Implement Backups
perfectsense/gyro-aws-provider pull request #430
Opened 2021-03-22 15:35 UTC by harjain99

Fixes #418

2021-03-29 21:08 UTC, deepanjan90 requested changes
1st Pass
 - Inline comments
 - Add License snippet to all java files
 - Use paginators for the finders
 - Add packgeinfo file to the package

2021-03-29 21:08 UTC, deepanjan90 commented on examples/backup/backup.gyro
> +    aliases: ["alias/backup-example"]
```suggestion
    aliases: ["alias/backup-selection-example"]
```

2021-03-29 21:08 UTC, deepanjan90 commented on examples/backup/backup.gyro
> +        Name: "kms-example"
```suggestion
        Name: "kms-for-backup-selection-example"
```

2021-04-08 18:20 UTC, deepanjan90 requested changes
2nd pass
 -Inline changes
 - Add @subresource doc tags

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupCopyAction.java
> +        return String.format("Vault: %s, Lifecycle: (%s,  %s)", getDestinationBackupVault().getName(),
```suggestion
        return String.format("with vault: %s and lifecycle: (%s,  %s)", getDestinationBackupVault().getName(),
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupCondition.java
> +            "Type: %s, Key: %s, Value: %s",
```suggestion
            "with type: %s, key: %s and value: %s",
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupCondition.java
> +    private String conditionKey;
```suggestion
    private String key;
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupCondition.java
> +    private ConditionType conditionType;
```suggestion
    private ConditionType type;
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupCondition.java
> +    private String conditionValue;
```suggestion
    private String value;
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/AdvancedBackupSetting.java
> +        return String.format("Resource Type: %s, Options: (%s)", getResourceType(), getBackupOptions().toString());
```suggestion
        return String.format("with resource type: %s and options: (%s)", getResourceType(), getBackupOptions().toString());
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupRule.java
> +        return String.format("Rule name: %s", getName());
```suggestion
        return getName();
```

2021-04-08 18:20 UTC, deepanjan90 commented on src/main/java/gyro/aws/backup/BackupLifecycle.java
> +    private Long moveToColdStorageAfterDays;
What if a user does not give any value ?

2021-04-09 20:08 UTC, harjain99 commented on src/main/java/gyro/aws/backup/BackupLifecycle.java
> +    private Long moveToColdStorageAfterDays;
It never transitions to cold storage.

2021-04-14 14:12 UTC, deepanjan90 approved these changes

2021-04-14 14:13 UTC, merged