Implement Event Bridge
perfectsense/gyro-aws-provider pull request #537
Opened 2022-01-05 23:50 UTC by deepanjan90

Fixes: #536

2022-01-25 21:49 UTC, harjain99 requested changes
Add EventBusRuleResource example file.
Implement TargetFinder
Add `// Read-only` comment for output fields.
Some of the abbreviations are not consistent (e.g. iam vs IAM, ecs vs ECS)

2022-01-25 21:49 UTC, harjain99 commented on src/main/java/gyro/aws/eventbridge/PlacementStrategy.java
> +    @Required
Add `@ValidStrings`

2022-01-25 21:49 UTC, harjain99 commented on src/main/java/gyro/aws/eventbridge/RedshiftDataParameter.java
> +     * The user name for teh database.
```suggestion
     * The user name for the database.
```

2022-01-25 21:49 UTC, harjain99 commented on src/main/java/gyro/aws/eventbridge/RedshiftDataParameter.java
> +     * Indicates whether to send an event back to EventBridge after the SQL statement runs.
```suggestion
     * When set to ``true``, an event is sent back to EventBridge after the SQL statement runs.
```

2022-01-25 21:49 UTC, harjain99 commented on src/main/java/gyro/aws/eventbridge/TargetResource.java
> +    private String arn;
Should probably be renamed to something like `sourceArn` for clarity.

2022-02-03 17:51 UTC, deepanjan90 commented on src/main/java/gyro/aws/eventbridge/BatchRetryStrategy.java
> +        return String.format("retry attempts - %s", getAttempts());
The super parent for this is target, which belongs to Rule as a list, thus the primary key

2022-02-03 18:00 UTC, deepanjan90 commented on src/main/java/gyro/aws/eventbridge/DeadLetterConfig.java
> +    private String arn;
The @id field for the queue resource is set to the queue url while this diffable needs arn, so is a mismatch

2022-02-03 20:56 UTC, deepanjan90 commented on src/main/java/gyro/aws/eventbridge/TargetResource.java
> +    private String arn;
Keeping it the same being consistent with the api.

2022-02-03 20:59 UTC, deepanjan90 commented
TargetResource is a subresource thus not needing a finder.

2022-05-19 13:06 UTC, harjain99 requested changes

2022-05-19 19:50 UTC, harjain99 approved these changes

2022-05-19 20:39 UTC, merged