Support finding ACM's using arn
perfectsense/gyro-aws-provider pull request #592
Opened 2022-10-24 16:02 UTC by deepanjan90

2022-10-28 00:34 UTC, mlivas commented on src/main/java/gyro/aws/acm/AcmCertificateFinder.java
> +        List<String> certArns = new ArrayList<>();
```suggestion
        Set<String> certArns = new LinkedHashSet<>();
```
Should this collection of ARNs be a `Set` to prevent duplicate results? Using a `LinkedHashSet` will preserve iteration order.

2022-11-07 16:17 UTC, harjain99 requested changes
The `certificate-status` filter is currently being ignored if it's the only filter present. We might need to add the `filterPresent = true;` at line 115.

2022-11-07 16:17 UTC, harjain99 commented on src/main/java/gyro/aws/acm/AcmCertificateFinder.java
> +            certArns.add(filters.get("arn"));
Currently, this does an `OR` operation instead of an `AND` if there are 2 filters and one of them is the `arn`.
```suggestion
            certArns.removeIf(a -> !a.equals(filters.get("arn")));
```

2023-01-04 20:38 UTC, deepanjan90 commented on src/main/java/gyro/aws/acm/AcmCertificateFinder.java
> +            certArns.add(filters.get("arn"));
It is doing an `and` operation as the conditional block is not in an `else` state.
Adding the suggestion form Matt for using sets also takes care of the duplicates.

2023-01-16 15:34 UTC, harjain99 approved these changes

2023-01-16 19:58 UTC, merged