Add writer endpoint type For database clusters
perfectsense/gyro-aws-provider pull request #660
Opened 2024-09-13 17:43 UTC by harjain99

2024-09-25 16:39 UTC, deepanjan90 commented on src/main/java/gyro/aws/rds/DbClusterEndpointResource.java
> +        String engine = getDbCluster().getEngine();
Potential NPE if `getDbCluster()` is null.

Even though it is a required field, the validations are checked all together.
Thus if a user does not specify the `db-cluster` field it will result in a NPE.

We should ignore this validation if the field is null, as the `@Required` will kick in.

2024-09-25 16:42 UTC, deepanjan90 commented on src/main/java/gyro/aws/rds/DbClusterEndpointResource.java
> +     * The type of the endpoint. Note: For Aurora, WRITER is not used.
```suggestion
     * The type of the endpoint. Cannot be set to ``WRITER`` if 'db-cluster' is set to ``Aurora``.
```

2024-09-25 16:43 UTC, deepanjan90 requested changes
2 minor changes

2024-09-27 20:09 UTC, Russsnizza commented on src/main/java/gyro/aws/rds/DbClusterEndpointResource.java
> +        String engine = getDbCluster().getEngine();
Got it, just updated it.

2024-10-01 20:10 UTC, deepanjan90 approved these changes

2024-10-01 20:14 UTC, merged