INFRA-619: Sort availability zones for db cluster
perfectsense/gyro-aws-provider pull request #662
Opened 2024-09-19 16:27 UTC by Russsnizza

## Description
This pull request addresses the need to maintain a consistently sorted order of 'availability zones' in our code.

## Changes
The setter method now takes the input list of availability zones, creates a new modifiable list from it, sorts this list, and assigns it back to the availabilityZones field.

[Jira Ticket](https://perfectsense.atlassian.net/browse/INFRA-619)

2024-09-25 15:29 UTC, harjain99 commented on src/main/java/gyro/aws/rds/DbClusterResource.java
> +        List<String> modifiableList = new ArrayList<>(availabilityZones); // creates a new modifiable list
We probably shouldn't blindly create a new list every time.
We should handle the conversion in the copyFrom.

```
    @Override
    public void copyFrom(DBCluster cluster) {
        setAvailabilityZones(new ArrayList<>(cluster.availabilityZones()));
```

2024-09-25 15:29 UTC, harjain99 commented on src/main/java/gyro/aws/rds/DbClusterResource.java
> +        Collections.sort(modifiableList);
The sort should take place on the getter instead.

2024-09-25 15:30 UTC, harjain99 requested changes
Added comments

2024-09-27 17:11 UTC, Russsnizza commented
Updated

2024-10-01 19:05 UTC, harjain99 approved these changes

2024-10-01 19:07 UTC, merged