Add null pointer checks for improved error handling
perfectsense/gyro-aws-provider pull request #664
Opened 2024-09-19 23:18 UTC by Russsnizza

## Description
This PR introduces necessary null pointer checks across several methods to prevent potential `NullPointerExceptions`. 

[Jira Ticket](https://perfectsense.atlassian.net/browse/INFRA-621)

2024-09-25 15:39 UTC, harjain99 requested changes
Added requested changes

2024-09-25 15:39 UTC, harjain99 commented on src/main/java/gyro/aws/rds/DbClusterResource.java
> +                    .allocatedStorage(getAllocatedStorage() == null ? null : getAllocatedStorage())
We should need a ternary operator here, `getAllocatedStorage()` will also return null if `allocated-storage` is null.

2024-09-25 15:39 UTC, harjain99 commented on src/main/java/gyro/aws/rds/DbClusterResource.java
> +                    .allocatedStorage(getAllocatedStorage() == null ? null : getAllocatedStorage())
same as above

2024-09-26 20:22 UTC, Russsnizza commented
Updated.

2024-10-01 20:14 UTC, harjain99 approved these changes

2024-10-01 20:14 UTC, merged