INFRA-623: Convert db subnet group subnets into list
perfectsense/gyro-aws-provider pull request #666
Opened 2024-09-24 14:02 UTC by Russsnizza

## Description
This PR refactors the DBSubnetGroupResource class. The setSubnets() and getSubnets() methods now work with a List instead of a Set. All references to these methods have been updated accordingly.

2024-09-25 16:04 UTC, harjain99 requested changes
Minor requested change. the rest looks good

2024-09-25 16:04 UTC, harjain99 commented on src/main/java/gyro/aws/rds/DbSubnetGroupResource.java
> +}
Add newline at the EOF

2024-09-25 19:28 UTC, Russsnizza commented on src/main/java/gyro/aws/rds/DbSubnetGroupResource.java
> +}
New line added.

2024-10-01 20:48 UTC, harjain99 approved these changes

2024-10-01 20:48 UTC, merged